name: Feature Request
description: Propose a new feature or enhancement
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What should be added or changed?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this needed? What problem does it solve?
    validations:
      required: true
  - type: dropdown
    id: spec_impact
    attributes:
      label: Specification impact
      options:
        - No
        - Yes (requires spec update)
        - Unsure
    validations:
      required: true
